import { ICategoryIcon } from './types'
import {
  HiOutlineAcademicCap,
  HiOutlineAnnotation,
  HiOutlineBookOpen,
  HiOutlineBriefcase,
  HiOutlineCamera,
  HiOutlineCash,
  HiOutlineDesktopComputer,
  HiOutlineFilm,
  HiOutlineFolderOpen,
  HiOutlineGift,
  HiOutlineHeart,
  HiOutlineLockClosed,
  HiOutlineMail,
  HiOutlineMusicNote,
  HiOutlineNewspaper,
  HiOutlinePhone,
  HiOutlinePhotograph,
  HiOutlinePrinter,
  HiOutlinePuzzle,
  HiOutlineRefresh,
  HiOutlineShoppingBag,
  HiOutlineShoppingCart,
  HiOutlineSparkles,
  HiOutlineStar,
  HiOutlineSupport,
  HiOutlineTag,
  HiOutlineTranslate,
  HiOutlineTruck,
  HiOutlineUser,
  HiOutlineVideoCamera,
} from 'react-icons/hi'

export const categoryIcons: ICategoryIcon[] = [
  {
    id: 0,
    name: 'default',
    icon: HiOutlineTag,
  },
  {
    id: 1,
    name: 'academic',
    icon: HiOutlineAcademicCap,
  },
  {
    id: 2,
    name: 'message',
    icon: HiOutlineAnnotation,
  },
  {
    id: 3,
    name: 'book',
    icon: HiOutlineBookOpen,
  },
  {
    id: 4,
    name: 'work',
    icon: HiOutlineBriefcase,
  },
  {
    id: 5,
    name: 'camera',
    icon: HiOutlineCamera,
  },
  {
    id: 6,
    name: 'cash',
    icon: HiOutlineCash,
  },
  {
    id: 7,
    name: 'film',
    icon: HiOutlineFilm,
  },
  {
    id: 8,
    name: 'folder',
    icon: HiOutlineFolderOpen,
  },
  {
    id: 9,
    name: 'gift',
    icon: HiOutlineGift,
  },
  {
    id: 10,
    name: 'heart',
    icon: HiOutlineHeart,
  },
  {
    id: 11,
    name: 'mail',
    icon: HiOutlineMail,
  },
  {
    id: 12,
    name: 'desktop',
    icon: HiOutlineDesktopComputer,
  },
  {
    id: 13,
    name: 'newspaper',
    icon: HiOutlineNewspaper,
  },
  {
    id: 14,
    name: 'phone',
    icon: HiOutlinePhone,
  },
  {
    id: 15,
    name: 'music',
    icon: HiOutlineMusicNote,
  },
  {
    id: 16,
    name: 'image',
    icon: HiOutlinePhotograph,
  },
  {
    id: 17,
    name: 'puzzle',
    icon: HiOutlinePuzzle,
  },
  {
    id: 18,
    name: 'shoppingbag',
    icon: HiOutlineShoppingBag,
  },
  {
    id: 19,
    name: 'shoppingcart',
    icon: HiOutlineShoppingCart,
  },
  {
    id: 20,
    name: 'sparkles',
    icon: HiOutlineSparkles,
  },
  {
    id: 21,
    name: 'star',
    icon: HiOutlineStar,
  },
  {
    id: 22,
    name: 'translate',
    icon: HiOutlineTranslate,
  },
  {
    id: 23,
    name: 'truck',
    icon: HiOutlineTruck,
  },
  {
    id: 24,
    name: 'camera',
    icon: HiOutlineVideoCamera,
  },
  {
    id: 25,
    name: 'user',
    icon: HiOutlineUser,
  },
  {
    id: 26,
    name: 'support',
    icon: HiOutlineSupport,
  },
  {
    id: 27,
    name: 'printer',
    icon: HiOutlinePrinter,
  },
  {
    id: 28,
    name: 'refresh',
    icon: HiOutlineRefresh,
  },
  {
    id: 29,
    name: 'lock',
    icon: HiOutlineLockClosed,
  },
]
